[package]
name = "tui-widget-list"
version = "0.3.1"
edition = "2021"
authors = ["preiter <phil.reiter93@gmail.com>"]
description = "Widget List for TUI/Ratatui"
repository = "https://github.com/preiter93/tui-widget-list"
keywords = ["tui", "ratatui", "widget", "list", "widgetlist"]
readme = "README.md"
license = "MIT"

[dependencies]
crossterm = "0.*"
ratatui = "0.*"

[[example]]
name = "simple"

[[example]]
name = "paragraph"

[[example]]
name = "mixed"
