[package]
name = "tui-widget-list"
version = "0.7.2"
edition = "2021"
authors = ["preiter <phil.reiter93@gmail.com>"]
description = "Widget List for TUI/Ratatui"
repository = "https://github.com/preiter93/tui-widget-list"
keywords = ["tui", "ratatui", "widget", "list", "widgetlist"]
readme = "README.md"
license = "MIT"

[dependencies]
ratatui = "0.26"

[dev-dependencies]
crossterm = "0.27"

[[example]]
name = "simple"

[[example]]
name = "paragraph"

[[example]]
name = "mixed"

[[example]]
name = "demo"
